version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - marvel-net

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - marvel-net

networks:
  marvel-net:
